"""Code quality & syntax validation for long-sequence extraction.

Ports the production-proven rule sets into one validator:

  * StarCoder2 / The Stack v2 text gates (arXiv:2402.19173):
        avg line length <= 100, max line <= 1000, lines <= 100k,
        alphabetic fraction >= 25%, autogenerated headers,
        encoded-data regexes (base64 / hex / unicode escapes)
  * OpenCoder RefineCode structural gates (arXiv:2411.04905,
    github.com/OpenCoder-llm/opc_data_filtering):
        long-string-line fraction, long-string-char fraction,
        hex-char proportion, duplicate-line ratio
  * AST / parse-tree syntax validation:
        Python via stdlib `ast`, all other languages via tree-sitter
        grammars (root `has_error` rejects truncation & garbage), with a
        tsx-grammar fallback for TypeScript files containing JSX.

Entry point:
    validate_code(text, lang) -> (ok: bool, failures: list[str])

Missing tree-sitter grammars raise at use time (hard fail by design —
silent degradation would defeat the quality contract).
"""

import re
import warnings
from typing import Dict, List, Optional, Tuple

# ── StarCoder2 text gates ────────────────────────────────────────────
MAX_AVG_LINE_LEN = 100
MAX_LINE_LEN = 1000
MAX_LINES = 100_000
MIN_ALPHA_FRACTION = 0.25
MAX_NON_ASCII_FRACTION = 0.10

_AUTOGEN_HEADERS = (
    "auto-generated", "autogenerated", "automatically generated",
    "generated automatically", "this file is generated",
)

_RE_BASE64 = re.compile(r"[a-zA-Z0-9+/\n=]{64,}")
_RE_HEX_SEQ = re.compile(r"(?:\b(?:0x|\\x)?[0-9a-fA-F]{2}(?:,|\b\s*)){8,}")
_RE_UNICODE = re.compile(r"(?:\\u[0-9a-fA-F]{4}){8,}")

# ── OpenCoder structural gates ───────────────────────────────────────
MAX_LONG_STRING_LINE_FRAC = 0.2   # lines dominated by one long string
MAX_LONG_STRING_CHAR_FRAC = 0.4   # chars inside >20-char strings
MAX_HEX_CHAR_FRACTION = 0.40   # encoded dumps are >60%; real code ~15-25%
MAX_DUP_LINE_FRACTION = 0.30
MAX_COMMENT_RATIO = 0.60
MIN_TOPLEVEL_DEFS = 2

_COMMENT_PREFIX = {"python": "#", "javascript": "//", "typescript": "//",
                   "java": "//", "c": "//", "cpp": "//", "go": "//",
                   "rust": "//"}

# tree-sitter top-level "definition-ish" node types per language
_TOPLEVEL_DEF_TYPES = {
    "javascript": {"function_declaration", "class_declaration",
                   "export_statement", "lexical_declaration",
                   "variable_declaration"},
    "typescript": {"function_declaration", "class_declaration",
                   "export_statement", "lexical_declaration",
                   "variable_declaration", "abstract_class_declaration",
                   "interface_declaration", "enum_declaration"},
    "java": {"class_declaration", "interface_declaration", "enum_declaration",
             "method_declaration", "annotation_type_declaration"},
    "c": {"function_definition", "declaration", "struct_specifier",
          "preproc_function_def", "preproc_ifdef"},
    "cpp": {"function_definition", "declaration", "struct_specifier",
            "class_specifier", "namespace_definition", "template_declaration",
            "preproc_function_def"},
    "go": {"function_declaration", "method_declaration", "type_declaration",
           "var_declaration", "const_declaration"},
    "rust": {"function_item", "struct_item", "enum_item", "impl_item",
             "trait_item", "mod_item", "const_item", "type_item"},
}

# ── tree-sitter registry (lazy) ──────────────────────────────────────
_TS_LANGUAGE_SPECS = {
    "javascript": ("tree_sitter_javascript", None),
    "typescript": ("tree_sitter_typescript", "language_typescript"),
    "tsx": ("tree_sitter_typescript", "language_tsx"),
    "java": ("tree_sitter_java", None),
    "c": ("tree_sitter_c", None),
    "cpp": ("tree_sitter_cpp", None),
    "go": ("tree_sitter_go", None),
    "rust": ("tree_sitter_rust", None),
}
_parsers: Dict[str, "Parser"] = {}
_warned_missing: set = set()  # languages for which we've already warned


def _get_parser(lang: str):
    """Lazily build a tree-sitter Parser; hard-fail if grammar missing."""
    if lang in _parsers:
        return _parsers[lang]
    if lang not in _TS_LANGUAGE_SPECS:
        raise ValueError(f"no tree-sitter grammar configured for {lang!r}; "
                         f"available: {sorted(_TS_LANGUAGE_SPECS)}")
    module_name, fn_name = _TS_LANGUAGE_SPECS[lang]
    try:
        import importlib
        mod = importlib.import_module(module_name)
        ptr = getattr(mod, fn_name)() if fn_name else mod.language()
    except ImportError as e:
        raise ImportError(
            f"tree-sitter grammar package {module_name!r} is required for "
            f"code validation (pip install {module_name.replace('_', '-')})"
        ) from e
    from tree_sitter import Language, Parser
    parser = Parser(Language(ptr))
    _parsers[lang] = parser
    return parser


# ── helpers ──────────────────────────────────────────────────────────

def _frac(numer: float, denom: float) -> float:
    return numer / denom if denom else 0.0


def _check_encoded_data(text: str, failures: List[str]) -> None:
    """StarCoder2 encoded-data filter: base64 / hex / unicode-escape dumps."""
    n = len(text)
    for name, rx in (("base64", _RE_BASE64), ("hex", _RE_HEX_SEQ),
                     ("unicode-escape", _RE_UNICODE)):
        total = 0
        longest = 0
        for m in rx.finditer(text):
            total += len(m.group())
            longest = max(longest, len(m.group()))
        if longest > 1024 or _frac(total, n) > 0.5:
            failures.append(f"encoded_data:{name}")
            return


def check_text_gates(text: str) -> List[str]:
    """StarCoder2-style whole-file gates. Returns list of failures."""
    failures: List[str] = []
    lines = text.split("\n")
    n_lines = len(lines)

    if n_lines > MAX_LINES:
        failures.append(f"lines>{MAX_LINES}")
        return failures  # nothing else matters for a data dump

    non_empty = [ln for ln in lines if ln.strip()]
    if non_empty:
        avg_len = sum(len(ln) for ln in non_empty) / len(non_empty)
        max_len = max(len(ln) for ln in lines)
        if avg_len > MAX_AVG_LINE_LEN:
            failures.append(f"avg_line_len>{MAX_AVG_LINE_LEN}")
        if max_len > MAX_LINE_LEN:
            failures.append(f"max_line_len>{MAX_LINE_LEN}")

    n_chars = len(text)
    alpha = sum(ch.isalpha() for ch in text)
    if _frac(alpha, n_chars) < MIN_ALPHA_FRACTION:
        failures.append(f"alpha_frac<{MIN_ALPHA_FRACTION}")

    non_ascii = sum(ord(ch) > 127 for ch in text)
    if _frac(non_ascii, n_chars) > MAX_NON_ASCII_FRACTION:
        failures.append(f"non_ascii_frac>{MAX_NON_ASCII_FRACTION}")

    head = "\n".join(lines[:5]).lower()
    if any(h in head for h in _AUTOGEN_HEADERS):
        failures.append("autogenerated_header")

    _check_encoded_data(text, failures)
    return failures


def check_code_structure(text: str, lang: str) -> List[str]:
    """OpenCoder-inspired structural gates. Returns list of failures."""
    failures: List[str] = []
    lines = [ln for ln in text.split("\n") if ln.strip()]
    if not lines:
        return ["empty"]

    # Long-string lines: a single token/string dominating a line (data dumps)
    long_string_lines = sum(
        1 for ln in lines
        if len(ln) > 200 or len(max(ln.split('"'), default="")) > 100
    )
    if _frac(long_string_lines, len(lines)) > MAX_LONG_STRING_LINE_FRAC:
        failures.append(f"long_string_lines>{MAX_LONG_STRING_LINE_FRAC}")

    # Chars inside very long "word-like" strings (base64/hash/url junk)
    long_word_chars = sum(
        len(w) for w in re.split(r'["\'\s]', text) if len(w) > 20
    )
    if _frac(long_word_chars, len(text)) > MAX_LONG_STRING_CHAR_FRAC:
        failures.append(f"long_string_chars>{MAX_LONG_STRING_CHAR_FRAC}")

    hex_chars = sum(ch in "0123456789abcdefABCDEF" for ch in text)
    if _frac(hex_chars, len(text)) > MAX_HEX_CHAR_FRACTION:
        failures.append(f"hex_frac>{MAX_HEX_CHAR_FRACTION}")

    # Duplicate non-empty line ratio (copy-pasted blocks / data dumps)
    dup = len(lines) - len(set(lines))
    if _frac(dup, len(lines)) > MAX_DUP_LINE_FRACTION:
        failures.append(f"dup_lines>{MAX_DUP_LINE_FRACTION}")

    # Comment ratio
    prefix = _COMMENT_PREFIX.get(lang)
    if prefix:
        comment_lines = sum(1 for ln in lines if ln.lstrip().startswith(prefix))
        if _frac(comment_lines, len(lines)) > MAX_COMMENT_RATIO:
            failures.append(f"comment_ratio>{MAX_COMMENT_RATIO}")

    return failures


# ── syntax validation ────────────────────────────────────────────────

def _python_syntax_and_defs(text: str) -> Tuple[bool, List[str]]:
    """stdlib ast: exact parse + top-level definition count."""
    import ast
    failures: List[str] = []
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", SyntaxWarning)
            tree = ast.parse(text)
    except SyntaxError as e:
        return False, [f"python_syntax_error:{e.lineno}"]
    defs = sum(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef,
                              ast.ClassDef)) for n in tree.body)
    if defs < MIN_TOPLEVEL_DEFS:
        failures.append(f"toplevel_defs<{MIN_TOPLEVEL_DEFS}")

    # OpenCoder language-specific: stub files full of `pass`
    n_lines = [ln for ln in text.split("\n") if ln.strip()]
    pass_lines = sum(1 for ln in n_lines if ln.strip() == "pass")
    if n_lines and _frac(pass_lines, len(n_lines)) > 0.3:
        failures.append("python_stub_pass_ratio")
    return True, failures


def _treesitter_syntax_and_defs(text: str, lang: str) -> Tuple[bool, List[str]]:
    """tree-sitter parse: has_error reject + top-level definition count."""
    failures: List[str] = []
    try:
        parser = _get_parser(lang)
    except ImportError:
        if lang not in _warned_missing:
            _warned_missing.add(lang)
            print(f"[code_ast_validator] WARNING: tree-sitter grammar for "
                  f"{lang!r} not installed — AST validation skipped. "
                  f"Install with: pip install tree-sitter-{lang}")
        # Text + structural gates already ran; skip AST-only check.
        return True, []
    tree = parser.parse(text.encode("utf-8"))

    # TypeScript files with JSX fail the ts grammar — retry with tsx.
    if lang == "typescript" and tree.root_node.has_error:
        try:
            tsx_parser = _get_parser("tsx")
            tsx_tree = tsx_parser.parse(text.encode("utf-8"))
            if not tsx_tree.root_node.has_error:
                tree = tsx_tree
            else:
                return False, ["syntax_error"]
        except ImportError:
            return False, ["syntax_error"]
    elif tree.root_node.has_error:
        return False, ["syntax_error"]

    # Java convention: one top-level public class per file — count
    # methods/constructors anywhere in the tree instead of top-level defs.
    if lang == "java":
        methods = sum(1 for n in _walk(tree.root_node)
                      if n.type in ("method_declaration",
                                    "constructor_declaration"))
        if methods < MIN_TOPLEVEL_DEFS:
            failures.append(f"java_methods<{MIN_TOPLEVEL_DEFS}")
        return True, failures

    def_types = _TOPLEVEL_DEF_TYPES.get(lang, set())
    defs = sum(1 for child in tree.root_node.children
               if child.type in def_types)
    if defs < MIN_TOPLEVEL_DEFS:
        failures.append(f"toplevel_defs<{MIN_TOPLEVEL_DEFS}")
    return True, failures


def _walk(node):
    """Yield node and all descendants (iterative — no recursion limits)."""
    stack = [node]
    while stack:
        n = stack.pop()
        yield n
        stack.extend(n.children)


# ── entry point ──────────────────────────────────────────────────────

def validate_code(text: str, lang: str) -> Tuple[bool, List[str]]:
    """Full validation pipeline for one code document.

    Returns (ok, failures): ok=True means the doc passed every gate.
    """
    failures = check_text_gates(text)
    if failures:
        return False, failures

    failures = check_code_structure(text, lang)
    if failures:
        return False, failures

    if lang == "python":
        ok, syntax_failures = _python_syntax_and_defs(text)
    else:
        ok, syntax_failures = _treesitter_syntax_and_defs(text, lang)
    failures.extend(syntax_failures)
    return (not failures), failures


def has_syntax_error(text: str, lang: str) -> bool:
    """Lightweight syntax-only check (no structural gates)."""
    if lang == "python":
        import ast
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", SyntaxWarning)
                ast.parse(text)
            return False
        except SyntaxError:
            return True
    parser = _get_parser(lang)
    return parser.parse(text.encode("utf-8")).root_node.has_error
